### PR TITLE
Working on implementing stripe

### PR DESCRIPTION
**Pull request by PhilHart23**

### CODE REVIEW

**Comment by secantsquared** [comment]
@PhilHart23 Smart use of the draft pull reqs totally forgot about them.

**Comment by PhilHart23** [comment]
# Description
Created the billing components using Stripe, added a nav link to test it out. 

Please delete options that are not relevant.

- [ x] New feature (non-breaking change which adds functionality)


## Change status
- [x ] Complete, tested, ready to review and merge
- [ ] Complete, but not tested (may need new tests)
- [ ] Incomplete/work-in-progress, PR is for discussion/feedback

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

Tested it locally in the browser. Click on the go premium link up top and enter in the card details. Use 4242 4242 4242 4242 as the number and you can choose the the exp etc. Please note that the endpoint has not been created in the backend so it'll return 404 after you pressed send. 

# Checklist:

- [x ] My code follows the style guidelines of this project
- [x ] I have performed a self-review of my own code
- [x ] My code has been reviewed by at least one peer
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x ] New and existing unit tests pass locally with my changes
- [x ] There are no merge conflicts

**Review by TrevMike — APPROVED** [review]
Looks good to me. Phil walked with me on how the code works.

**Review by secantsquared — APPROVED** [review]
Looks solid. Nice work.

**Pull request merged**
